---
abstract: 'Language tag scanner'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  File::Temp: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Localizer-Scanner
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Localizer::Dictionary:
    file: lib/Localizer/Dictionary.pm
  Localizer::Scanner:
    file: lib/Localizer/Scanner.pm
    version: 0.03
  Localizer::Scanner::Perl:
    file: lib/Localizer/Scanner/Perl.pm
requires:
  Class::Accessor::Lite: 0.05
  perl: 5.010_001
resources:
  bugtracker: https://github.com/tokuhirom/Localizer-Scanner/issues
  homepage: https://github.com/tokuhirom/Localizer-Scanner
  repository: git://github.com/tokuhirom/Localizer-Scanner.git
version: 0.03
